### ISSUE TITLE
Handling of missing genotype data

### ISSUE THREAD

**Issue by Yaniv42** [grimmlab/permGWAS#3]
Hi.

I would like to confirm whether permGWAS handles missing genotype data.

When I provide a PLINK .bed file with missing genotypes I get this error:

```
Traceback (most recent call last):
  File "permGWAS.py", line 88, in <module>
    X, y, K, covs, positions, chrom, X_index = prep.load_and_prepare_data(args)
  File "/permGWAS/preprocessing/prepare_data.py", line 75, in load_and_prepare_data
    X = load_files.load_genotype_matrix(arguments.x, sample_index=sample_index[1])
  File "/permGWAS/preprocessing/load_files.py", line 140, in load_genotype_matrix
    raise Exception('Genotype not in additive encoding.')
Exception: Genotype not in additive encoding.
```

Thanks,
Yaniv

**Comment by dominikgrimm** [comment]
Dear Yaniv,

currently, we only support fully imputed genotype matrices. You can impute your data using Beagle or Impute2. 

Best wishes,
Dominik Grimm
